# Shell variables
# Generated by 'wal'
wallpaper='/usr/share/backgrounds/hefftorlinux/Hefftor_4k.png'

# Special
background='#0a0c0d'
foreground='#dfe0e3'
cursor='#dfe0e3'

# Colors
color0='#0a0c0d'
color1='#5B5E64'
color2='#6D6D71'
color3='#797985'
color4='#7F8487'
color5='#9B9CA1'
color6='#B6BAC8'
color7='#dfe0e3'
color8='#9c9c9e'
color9='#5B5E64'
color10='#6D6D71'
color11='#797985'
color12='#7F8487'
color13='#9B9CA1'
color14='#B6BAC8'
color15='#dfe0e3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
