--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/usr/share/backgrounds/hefftorlinux/Hefftor_4k.png"

-- Special
background="#0a0c0d"
foreground="#dfe0e3"
cursor="#dfe0e3"

-- Colors
color0="#0a0c0d"
color1="#5B5E64"
color2="#6D6D71"
color3="#797985"
color4="#7F8487"
color5="#9B9CA1"
color6="#B6BAC8"
color7="#dfe0e3"
color8="#9c9c9e"
color9="#5B5E64"
color10="#6D6D71"
color11="#797985"
color12="#7F8487"
color13="#9B9CA1"
color14="#B6BAC8"
color15="#dfe0e3"
